# Generated by Django 5.0.6 on 2024-06-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayHousings', '0003_product_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayhousing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
