# Generated by Django 5.0.6 on 2024-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayHousings', '0004_holidayhousing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayhousing',
            name='price',
            field=models.IntegerField(),
        ),
    ]
