# Generated by Django 5.0.6 on 2024-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolidayHousings', '0006_alter_cartitem_product_alter_holidayhousing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayhousing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='housing_images/'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
